const KEY='packme-v2';
const themes={day:{accent:'#e85d7a',bg1:'#fff5f7',bg2:'#eef8f5',photo:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'},city:{accent:'#7567c8',bg1:'#f1efff',bg2:'#fff7ee',photo:'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80'},beach:{accent:'#159aaf',bg1:'#e9fbfd',bg2:'#fff4de',photo:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'},mountain:{accent:'#5f8a70',bg1:'#edf5ee',bg2:'#faf2e6',photo:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80'},camp:{accent:'#b87339',bg1:'#fbefe2',bg2:'#eff5e8',photo:'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1200&q=80'}};
const types=[['day','🌷','Tagesausflug'],['city','🏙️','Städtereise'],['beach','🏖️','Strandurlaub'],['mountain','🏔️','Bergurlaub'],['camp','⛺','Camping']];
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{people:[{id:'me',name:'Ich',kind:'adult',shirt:1.15,pants:.6,underwear:1.15,socks:1.15},{id:'partner',name:'Partner',kind:'adult',shirt:1.15,pants:.6,underwear:1.15,socks:1.15},{id:'child',name:'Kind',kind:'child',diapers:5,shirt:1.2,pants:.7,socks:1.2}],trips:[],view:'home',current:null};
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function applyTheme(t){const x=themes[t]||themes.day;for(const [k,v] of Object.entries({'--accent':x.accent,'--bg1':x.bg1,'--bg2':x.bg2}))document.documentElement.style.setProperty(k,v)}
function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString('de-AT',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'})}
function ownerName(id){return id==='shared'?'Gemeinsam':db.people.find(p=>p.id===id)?.name||'Person'}
async function geocode(q){const u='https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=1&language=de&format=json';const r=await fetch(u);if(!r.ok)throw Error('Geocoding');const j=await r.json();if(!j.results?.length)throw Error('Ort nicht gefunden');return j.results[0]}
async function getWeather(lat,lon,date,days){const start=date,end=new Date(new Date(date+'T12:00:00').getTime()+(days-1)*86400000).toISOString().slice(0,10);const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&start_date=${start}&end_date=${end}`;const r=await fetch(u);if(!r.ok)throw Error('Wetter');return await r.json()}
function weatherSummary(w){if(!w?.daily)return null;const d=w.daily;return {max:Math.round(Math.max(...d.temperature_2m_max)),min:Math.round(Math.min(...d.temperature_2m_min)),rain:Math.max(...d.precipitation_probability_max),code:d.weather_code?.[0]??0}}
function codeIcon(c){if(c===0)return'☀️';if(c<=3)return'🌤️';if(c<=48)return'🌫️';if(c<=67)return'🌧️';if(c<=77)return'❄️';if(c<=82)return'🌦️';return'⛈️'}
function qty(n){return Math.max(1,Math.ceil(n))}
function add(items,name,owner,quantity,category='Sonstiges',reason=''){items.push({id:crypto.randomUUID(),name,owner,qty:qty(quantity),category,reason,done:false})}
function buildItems(trip,w){const items=[],days=trip.days;const hot=w?.max>=23,cool=w?.min<14,cold=w?.min<8,wet=w?.rain>=35;
 for(const id of trip.people){const p=db.people.find(x=>x.id===id);if(!p)continue;if(p.kind==='child'){add(items,'Windeln',id,(p.diapers??5)*days+2,'Hygiene','Tagesbedarf + Reserve');add(items,'Feuchttücher',id,1,'Hygiene');add(items,'Shirts',id,(p.shirt??1.2)*days+1,'Kleidung','Tagesoutfits + Reserve');add(items,'Hosen',id,(p.pants??.7)*days+1,'Kleidung');add(items,'Socken',id,(p.socks??1.2)*days+1,'Kleidung');add(items,'Wechseloutfits',id,Math.max(1,Math.ceil(days*.5)),'Kleidung');add(items,'Schnuller',id,2,'Kind');add(items,'Trinkflasche',id,1,'Kind');if(hot)add(items,'Sonnenhut',id,1,'Wetter');if(cold)add(items,'Warme Schicht',id,1,'Wetter');}else{add(items,'Shirts',id,(p.shirt??1.15)*days+1,'Kleidung');add(items,'Hosen',id,(p.pants??.6)*days+1,'Kleidung');add(items,'Unterwäsche',id,(p.underwear??1.15)*days+1,'Kleidung');add(items,'Socken',id,(p.socks??1.15)*days+1,'Kleidung');add(items,'Schlafsachen',id,1,'Kleidung');}}
 add(items,'Handy-Ladegerät','shared',1,'Technik');add(items,'Powerbank','shared',1,'Technik');add(items,'Taschentücher','shared',2,'Gemeinsam');
 if(hot)add(items,'Sonnencreme','shared',1,'Wetter','Sonnig/warm');if(wet)add(items,'Regenjacken','shared',trip.people.filter(id=>db.people.find(p=>p.id===id)?.kind==='adult').length,'Wetter','Regenwahrscheinlichkeit hoch');if(wet)add(items,'Regenschirm','shared',1,'Wetter');if(cool)add(items,'Jacken','shared',1,'Wetter');
 if(trip.type==='beach'){add(items,'Badesachen','shared',trip.people.length,'Aktivität');add(items,'Strandtücher','shared',trip.people.length,'Aktivität')}if(trip.type==='mountain'){add(items,'Wanderschuhe','shared',1,'Aktivität');add(items,'Rucksack','shared',1,'Aktivität')}if(trip.type==='camp'){add(items,'Taschenlampe','shared',1,'Camping');add(items,'Insektenschutz','shared',1,'Camping')}if(trip.type==='city'){add(items,'Bequeme Schuhe','shared',trip.people.length,'Aktivität')}if(trip.type==='day')add(items,'Getränke','shared',trip.people.length,'Essen & Trinken');
 add(items,'Kleine Reiseapotheke','shared',1,'Gemeinsam');return items}
function tripCard(t){const th=themes[t.type]||themes.day,done=t.items?.filter(i=>i.done).length||0,total=t.items?.length||0,pct=total?Math.round(done/total*100):0;return `<div class="trip-card" style="--card-photo:url('${th.photo}')" onclick="openTrip('${t.id}')"><div class="trip-photo"></div><div class="trip-info"><div class="row space"><div><b>${esc(t.name)}</b><div class="small">${esc(t.date)} · ${t.days} Tag${t.days>1?'e':''}</div></div><strong>${pct}%</strong></div><div class="progress"><i style="width:${pct}%"></i></div><div class="small">${t.weather?`${codeIcon(t.weather.code)} ${t.weather.max}° · Regen ${t.weather.rain}%`:'🌦️ Wetter wird geladen'}</div></div></div>`}
function shell(content){return `<div class="shell">${content}<nav class="nav"><button class="${db.view==='home'?'active':''}" onclick="go('home')">🏠<span>Reisen</span></button><button class="${db.view==='people'?'active':''}" onclick="go('people')">👥<span>Personen</span></button><button class="${db.view==='templates'?'active':''}" onclick="go('templates')">📋<span>Vorlagen</span></button><button class="${db.view==='more'?'active':''}" onclick="go('more')">•••<span>Mehr</span></button></nav></div>`}
function home(){applyTheme('day');return shell(`<header class="hero"><div class="eyebrow">Deine Abenteuer, deine Liste ♡</div><div class="title">PackMe</div><div class="sub">Pack. Erlebe. Genieße.</div></header><main class="content"><button class="btn" onclick="go('new')">＋ Neue Reise</button><h3>Meine Reisen</h3>${db.trips.map(tripCard).join('')||`<div class="empty">🧳<h3>Noch keine Reise</h3><p>Erstelle eine Reise und PackMe denkt beim Packen mit.</p></div>`}</main>`)}
function newView(){applyTheme('day');return shell(`<header class="hero"><button class="back" onclick="go('home')">‹ Zurück</button><div class="title">Neue Reise</div><div class="sub">Die Stimmung und Packlogik passen sich deinem Abenteuer an.</div></header><main class="content"><div class="card"><label>Wohin geht's?</label><input id="dest" class="input" placeholder="z. B. Velden, Prag, Gardasee"><label>Reiseart</label><div class="grid">${types.map(c=>`<button class="choice ${c[0]==='day'?'active':''}" data-type="${c[0]}" onclick="selectType(this)">${c[1]}<br><b>${c[2]}</b></button>`).join('')}</div><label>Datum</label><input id="date" type="date" class="input" value="${new Date().toISOString().slice(0,10)}"><label>Dauer</label><div class="stepper"><button onclick="step(-1)">−</button><strong id="days">1</strong><button onclick="step(1)">＋</button></div><label>Wer kommt mit?</label><div class="people">${db.people.map(p=>`<button class="person active" data-person="${p.id}" onclick="this.classList.toggle('active')">${p.kind==='child'?'👶':'👤'} ${esc(p.name)}</button>`).join('')}</div><label>Aktivitäten (optional)</label><div class="chips">${['Museum','Spazieren','Restaurant','Baden','Wandern','Shopping'].map(x=>`<button class="chip" onclick="this.classList.toggle('active')">${x}</button>`).join('')}</div></div><button class="btn wide" onclick="createTrip()">Checkliste erstellen →</button><p id="createStatus" class="muted center"></p></main>`)}
function step(n){const e=document.querySelector('#days');e.textContent=Math.max(1,+e.textContent+n)}
function selectType(el){document.querySelectorAll('[data-type]').forEach(x=>x.classList.remove('active'));el.classList.add('active');applyTheme(el.dataset.type)}
async function createTrip(){const dest=document.querySelector('#dest').value.trim()||'Mein Ausflug',date=document.querySelector('#date').value,days=+document.querySelector('#days').textContent,type=document.querySelector('.choice.active').dataset.type,people=[...document.querySelectorAll('[data-person].active')].map(x=>x.dataset.person),status=document.querySelector('#createStatus');status.textContent='📍 Ort wird gesucht und Wetter wird geladen …';let geo=null,w=null;try{geo=await geocode(dest);w=await getWeather(geo.latitude,geo.longitude,date,days)}catch(e){status.textContent='⚠️ Wetter konnte nicht geladen werden – die Packliste wird trotzdem erstellt.'}const t={id:crypto.randomUUID(),name:geo?.name||dest,date,days,type,people,location:geo,weather:weatherSummary(w),items:buildItems({days,type,people},weatherSummary(w)),createdAt:Date.now()};db.trips.unshift(t);save();openTrip(t.id)}
function openTrip(id){db.current=id;db.view='trip';render()}
function tripView(){const t=db.trips.find(x=>x.id===db.current);if(!t)return home();applyTheme(t.type);const th=themes[t.type]||themes.day,done=t.items.filter(i=>i.done).length,pct=t.items.length?Math.round(done/t.items.length*100):0;const groups=[...new Set(t.items.map(i=>i.owner))];const w=t.weather;return shell(`<header class="hero trip-hero" style="background-image:linear-gradient(135deg,${th.bg1},${th.bg2})"><button class="back" onclick="go('home')">‹ Reisen</button><div class="row space"><div><div class="title">${esc(t.name)}</div><div class="sub">${fmtDate(t.date)} · ${t.days} Tag${t.days>1?'e':''} · ${t.people.length} Personen</div></div><div class="percent">${pct}%</div></div><div class="progress"><i style="width:${pct}%"></i></div></header><main class="content"><div class="weather-card" style="background-image:url('${th.photo}')"><div class="weather-overlay"><div class="small">${t.location?esc(t.location.name):esc(t.name)}</div><div class="weather-big">${w?`${codeIcon(w.code)} ${w.max}°`: '🌦️'} </div><div>${w?`${w.min}° bis ${w.max}° · Regen ${w.rain}%`:'Wetter nicht verfügbar'}</div></div></div><div class="smart card"><b>🧠 PackMe denkt mit</b><span>${smartText(t,w)}</span></div><div class="row space"><h3>Packliste</h3><span class="muted">${done}/${t.items.length}</span></div>${groups.map(g=>`<section class="list-card"><div class="section-title">${g==='shared'?'🧳 Gemeinsam':'👤 '+esc(ownerName(g))}</div>${t.items.filter(i=>i.owner===g).map(itemRow).join('')}</section>`).join('')}</main><button class="fab" onclick="addItem()">＋</button>`)}
function smartText(t,w){if(!w)return'Keine Wetterdaten – die Grundliste ist trotzdem erstellt.';let bits=[];if(w.max>=23)bits.push('warm: Sonnenschutz');if(w.rain>=35)bits.push('Regenreserve');if(w.min<14)bits.push('zusätzliche Schicht');if(t.type==='beach')bits.push('Badesachen');if(t.type==='mountain')bits.push('Bergausrüstung');return bits.length?bits.join(' · '):'mildes Wetter: leichte, flexible Kleidung';}
function itemRow(i){return `<div class="item swipe" data-id="${i.id}"><div class="item-icon">${iconFor(i)}</div><div class="item-main"><div class="${i.done?'done':''}">${esc(i.name)}</div><div class="small muted">${i.qty} ×${i.reason?` · ${esc(i.reason)}`:''}</div></div><button class="iconbtn" onclick="toggleItem('${i.id}')">${i.done?'↩':'✓'}</button><button class="iconbtn danger" onclick="deleteItem('${i.id}')">×</button></div>`}
function iconFor(i){const n=i.name.toLowerCase();if(n.includes('windel'))return'🧷';if(n.includes('shirt'))return'👕';if(n.includes('hose'))return'👖';if(n.includes('sock'))return'🧦';if(n.includes('jack'))return'🧥';if(n.includes('sonnen'))return'🧴';if(n.includes('regen'))return'🌧️';if(n.includes('lade'))return'🔌';if(n.includes('schuh'))return'👟';if(n.includes('baden'))return'🩱';return'•'}
function toggleItem(id){const t=db.trips.find(x=>x.id===db.current),i=t.items.find(x=>x.id===id);if(i)i.done=!i.done;save();render()}
function deleteItem(id){const t=db.trips.find(x=>x.id===db.current);t.items=t.items.filter(x=>x.id!==id);save();render()}
function addItem(){const name=prompt('Was möchtest du hinzufügen?');if(!name)return;const q=prompt('Wie viele?','1');const t=db.trips.find(x=>x.id===db.current);t.items.push({id:crypto.randomUUID(),name,owner:'shared',qty:qty(+q||1),category:'Eigene Punkte',done:false});save();render()}
function peopleView(){applyTheme('day');return shell(`<header class="hero"><div class="eyebrow">Einmal anlegen, immer wieder verwenden</div><div class="title">Personen</div></header><main class="content">${db.people.map(p=>`<div class="card person-card"><div class="row space"><div><b>${p.kind==='child'?'👶':'👤'} ${esc(p.name)}</b><div class="small muted">${p.kind==='child'?'Kind':'Erwachsene Person'}</div></div><button class="iconbtn danger" onclick="removePerson('${p.id}')">×</button></div><div class="mini-grid"><div><span>${p.kind==='child'?'Windeln/Tag':'Shirts/Tag'}</span><b>${p.kind==='child'?(p.diapers??5):p.shirt}</b></div><div><span>${p.kind==='child'?'Shirts/Tag':'Unterwäsche/Tag'}</span><b>${p.kind==='child'?(p.shirt??1.2):p.underwear}</b></div></div></div>`).join('')}<button class="btn" onclick="addPerson()">＋ Person hinzufügen</button></main>`)}
function addPerson(){const name=prompt('Name?');if(!name)return;const child=confirm('Ist es ein Kind?');const p={id:crypto.randomUUID(),name,kind:child?'child':'adult'};if(child)Object.assign(p,{diapers:5,shirt:1.2,pants:.7,socks:1.2});else Object.assign(p,{shirt:1.15,pants:.6,underwear:1.15,socks:1.15});db.people.push(p);save();render()}
function removePerson(id){db.people=db.people.filter(p=>p.id!==id);save();render()}
function templates(){applyTheme('day');return shell(`<header class="hero"><div class="title">Vorlagen</div><div class="sub">Speichere fertige Reisen als Ausgangspunkt.</div></header><main class="content">${db.trips.slice(0,5).map(t=>`<div class="card row space"><div><b>${esc(t.name)}</b><div class="small muted">${t.days} Tag${t.days>1?'e':''} · ${t.items.length} Punkte</div></div><button class="btn smallbtn" onclick="duplicateTrip('${t.id}')">Duplizieren</button></div>`).join('')||'<div class="empty">📋<h3>Noch keine Vorlagen</h3><p>Deine Reisen erscheinen hier als wiederverwendbare Ausgangspunkte.</p></div>'}</main>`)}
function duplicateTrip(id){const old=db.trips.find(t=>t.id===id);if(!old)return;const t=JSON.parse(JSON.stringify(old));t.id=crypto.randomUUID();t.date=new Date().toISOString().slice(0,10);t.items=t.items.map(i=>({...i,id:crypto.randomUUID(),done:false}));db.trips.unshift(t);save();openTrip(t.id)}
function more(){applyTheme('day');return shell(`<header class="hero"><div class="title">Mehr</div></header><main class="content"><div class="card"><b>🌦️ Wetter</b><p class="muted">PackMe nutzt Geocoding und Wetterdaten von Open-Meteo, wenn eine Internetverbindung verfügbar ist.</p></div><div class="card"><b>👈➡️ Swipe</b><p class="muted">Rechts wischen = eingepackt. Links wischen = zurückstellen. Die Buttons funktionieren ebenfalls.</p></div><div class="card"><b>💾 Privat gespeichert</b><p class="muted">Reisen und Personenprofile werden lokal im Browser gespeichert.</p></div></main>`)}
function go(v){db.view=v;save();render()}
function render(){const c=db.view==='new'?newView():db.view==='trip'?tripView():db.view==='people'?peopleView():db.view==='templates'?templates():db.view==='more'?more():home();document.getElementById('app').innerHTML=c;if(db.view==='trip')enableSwipe()}
function enableSwipe(){document.querySelectorAll('.swipe').forEach(el=>{let sx=0;el.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>70){const t=db.trips.find(x=>x.id===db.current),i=t.items.find(x=>x.id===el.dataset.id);if(i)i.done=dx>0;save();render()}})})}
render();
