const KEY='packme-v6';
const themes={day:{accent:'#e76f8b',bg1:'#fff4f6',bg2:'#eef8f4',photo:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'},city:{accent:'#7567c8',bg1:'#f0efff',bg2:'#fff7ed',photo:'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80'},beach:{accent:'#1499ad',bg1:'#e9fbfd',bg2:'#fff3dc',photo:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'},mountain:{accent:'#5d886d',bg1:'#edf5ee',bg2:'#faf1e4',photo:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3e?auto=format&fit=crop&w=1200&q=80'},camp:{accent:'#b8753a',bg1:'#fbefe2',bg2:'#eff5e8',photo:'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1200&q=80'}};
const types=[['day','🌷','Tagesausflug'],['city','🏙️','Städtereise'],['beach','🏖️','Strandurlaub'],['mountain','🏔️','Bergurlaub'],['camp','⛺','Camping']];
const defaultDB={people:[{id:'me',name:'Ich',kind:'adult',shirt:1.1,pants:.55,underwear:1.1,socks:1.1},{id:'partner',name:'Partner',kind:'adult',shirt:1.1,pants:.55,underwear:1.1,socks:1.1},{id:'child',name:'Kind',kind:'child',age:1,diapers:5,shirt:1.2,pants:.7,socks:1.2}],trips:[],view:'home',current:null};
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'null')||defaultDB}catch{db=defaultDB}
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function applyTheme(t){const x=themes[t]||themes.day;document.documentElement.style.setProperty('--accent',x.accent);document.documentElement.style.setProperty('--bg1',x.bg1);document.documentElement.style.setProperty('--bg2',x.bg2)}
function fmtDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString('de-AT',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}):''} function ownerName(id){return id==='shared'?'Gemeinsam':db.people.find(p=>p.id===id)?.name||'Person'}
async function geocode(q){const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=1&language=de&format=json');if(!r.ok)throw Error();const j=await r.json();if(!j.results?.length)throw Error();return j.results[0]}
async function getWeather(lat,lon,date,days){const end=new Date(new Date(date+'T12:00:00').getTime()+(days-1)*86400000).toISOString().slice(0,10);const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&start_date=${date}&end_date=${end}`;const r=await fetch(u);if(!r.ok)throw Error();return r.json()}
function weatherSummary(w){if(!w?.daily)return null;const d=w.daily;return{max:Math.round(Math.max(...d.temperature_2m_max)),min:Math.round(Math.min(...d.temperature_2m_min)),rain:Math.max(...d.precipitation_probability_max),code:d.weather_code?.[0]??0}}function codeIcon(c){if(c===0)return'☀️';if(c<=3)return'🌤️';if(c<=48)return'🌫️';if(c<=67)return'🌧️';if(c<=77)return'❄️';if(c<=82)return'🌦️';return'⛈️'}
function add(a,name,owner,qty,cat='Sonstiges',reason=''){a.push({id:uid(),name,owner,qty:Math.max(1,Math.ceil(qty)),category:cat,reason,done:false})}
function buildItems(t,w){
 const a=[],day=t.days===1&&t.type==='day',overnight=t.days>1||t.overnight,hot=(w?.max??20)>=23,cool=(w?.min??12)<14,cold=(w?.min??12)<8,wet=(w?.rain??0)>=35,veryWet=(w?.rain??0)>=65,acts=new Set(t.activities||[]);
 for(const id of t.people){const p=db.people.find(x=>x.id===id);if(!p)continue;
  if(p.kind==='child'){
   add(a,'Windeln',id,day?Math.max(4,(p.diapers||5)+2):(p.diapers||5)*t.days+3,'Hygiene',day?'Tagesbedarf + 2 Reserve':'Tagesbedarf × Reisetage + 3 Reserve');
   ['Feuchttücher','Wickelunterlage','Wundschutzcreme'].forEach(n=>add(a,n,id,1,'Hygiene'));
   if(day){add(a,'Shirt',id,1,'Kleidung','Wird getragen');add(a,'Hose',id,1,'Kleidung','Wird getragen');add(a,'Socken',id,1,'Kleidung','Wird getragen');add(a,'Wechseloutfit komplett',id,1,'Kleidung','Für Essen, Kleckern, Nässe');add(a,'Zusätzliches Shirt',id,1,'Kleidung','Kleine Reserve')}else{add(a,'Shirts',id,Math.ceil((p.shirt||1.2)*t.days)+1,'Kleidung','Tagesbedarf + Reserve');add(a,'Hosen',id,Math.ceil((p.pants||.7)*t.days)+1,'Kleidung','Tagesbedarf + Reserve');add(a,'Socken',id,Math.ceil((p.socks||1.2)*t.days)+1,'Kleidung','Tagesbedarf + Reserve');add(a,'Wechseloutfits',id,Math.max(1,Math.ceil(t.days*.5)),'Kleidung','Für Kleckern/Nässe');add(a,'Schlafanzug',id,2,'Schlafen','1 + Reserve');add(a,'Schlafsack',id,1,'Schlafen')}
   add(a,'Lätzchen',id,day?2:Math.max(3,t.days),'Essen');add(a,'Trinkflasche',id,1,'Essen');add(a,'Snacks',id,1,'Essen');add(a,'Löffel/Besteck',id,1,'Essen');add(a,'Schnuller',id,2,'Baby','1 Reserve');add(a,'Schnullerbox',id,1,'Baby');add(a,'Lieblingsspielzeug',id,1,'Baby');add(a,'Kleines Buch',id,1,'Baby');
   if(overnight){add(a,'Reisebett',id,1,'Schlafen','Falls Unterkunft kein Kinderbett bereitstellt');add(a,'Spannbettlaken',id,1,'Schlafen');add(a,'Babyphone',id,1,'Technik');add(a,'Nachtlicht',id,1,'Schlafen')}
   if(hot){add(a,'Sonnenhut',id,1,'Wetter','Sonniges/warmes Wetter');add(a,'Sonnencreme',id,1,'Wetter','Sonnenschutz')}if(cold){add(a,'Warme Jacke',id,1,'Wetter');add(a,'Mütze',id,1,'Wetter')}if(wet)add(a,'Regenjacke',id,1,'Wetter','Regenwahrscheinlichkeit ≥ 35 %');
  }else{
   if(day){add(a,'Wechselshirt',id,1,'Kleidung','Kleidung wird getragen');add(a,'Zusätzliche Unterwäsche',id,1,'Kleidung','Sicherheitsreserve');add(a,'Zusätzliche Socken',id,1,'Kleidung','Sicherheitsreserve')}else{add(a,'Shirts',id,Math.ceil((p.shirt||1.1)*t.days)+1,'Kleidung','Tagesbedarf + Reserve');add(a,'Hosen',id,Math.ceil((p.pants||.55)*t.days)+1,'Kleidung','Mehrfach tragbar');add(a,'Unterwäsche',id,Math.ceil((p.underwear||1.1)*t.days)+1,'Kleidung','Tagesbedarf + Reserve');add(a,'Socken',id,Math.ceil((p.socks||1.1)*t.days)+1,'Kleidung','Tagesbedarf + Reserve');add(a,'Schlafsachen',id,1,'Schlafen','Übernachtung')}
   add(a,'Sonnenbrille',id,1,'Persönlich');add(a,'Taschentücher',id,1,'Persönlich');add(a,'Persönliche Medikamente',id,1,'Gesundheit');if(overnight){add(a,'Zahnbürste',id,1,'Pflege');add(a,'Zahnpasta',id,1,'Pflege');add(a,'Deo',id,1,'Pflege');add(a,'Duschgel',id,1,'Pflege','Falls Unterkunft nicht vorhanden');add(a,'Shampoo',id,1,'Pflege');add(a,'Haarbürste',id,1,'Pflege')}if(hot)add(a,'Sonnencreme',id,1,'Wetter');if(cool)add(a,'Leichte Jacke',id,1,'Wetter','Morgens/abends kühl');if(cold)add(a,'Warme Jacke',id,1,'Wetter','Unter 8 °C');if(wet)add(a,'Regenjacke',id,1,'Wetter','Regenwahrscheinlichkeit ≥ 35 %');
  }}
 add(a,'Handys','shared',t.people.length,'Technik');add(a,'Ladegeräte','shared',t.people.length,'Technik');add(a,'Powerbank','shared',1,'Technik');add(a,'Geldbörse','shared',1,'Dokumente');add(a,'Ausweise','shared',t.people.length,'Dokumente');add(a,'Taschentücher','shared',1,'Gemeinsam');add(a,'Handdesinfektion','shared',1,'Gesundheit');add(a,'Kleine Reiseapotheke','shared',1,'Gesundheit');add(a,'Pflaster','shared',1,'Gesundheit');add(a,'Müllbeutel','shared',3,'Gemeinsam');
 if(day){add(a,'Getränke','shared',t.people.length,'Essen & Trinken','Tagesausflug');add(a,'Snacks','shared',t.people.length,'Essen & Trinken','Tagesausflug');add(a,'Kinderwagen','shared',1,'Baby/Familie')}
 if(hot){add(a,'Große Sonnencreme','shared',1,'Wetter','Für die ganze Familie');add(a,'Sonnenhut-Reserve','shared',1,'Wetter','Reserve')}
 if(wet){add(a,'Regenschirm','shared',1,'Wetter','Regenwahrscheinlichkeit ≥ 35 %');if(veryWet)add(a,'Wasserdichte Tasche','shared',1,'Wetter','Hohe Regenwahrscheinlichkeit')}
 if(acts.has('Baden')||t.type==='beach'){add(a,'Badesachen','shared',t.people.length,'Aktivität');add(a,'Strandtücher','shared',t.people.length,'Aktivität');add(a,'Wasserfeste Tasche','shared',1,'Aktivität')}
 if(acts.has('Wandern')||t.type==='mountain'){add(a,'Wanderschuhe','shared',t.people.length,'Aktivität');add(a,'Tagesrucksack','shared',1,'Aktivität');add(a,'Wasserflaschen','shared',t.people.length,'Aktivität');add(a,'Blasenpflaster','shared',1,'Gesundheit')}
 if(acts.has('Restaurant'))add(a,'Kleines Abendoutfit','shared',t.people.length,'Aktivität','Restaurant/Abend');if(acts.has('Shopping')||t.type==='city')add(a,'Bequeme Schuhe','shared',t.people.length,'Aktivität','Viel Gehen');
 if(t.type==='camp'){add(a,'Taschenlampe','shared',1,'Camping');add(a,'Insektenschutz','shared',1,'Camping');add(a,'Mückenspray','shared',1,'Camping')}
 if(overnight){add(a,'Schmutzwäschebeutel','shared',1,'Organisation');add(a,'Wäsche-/Kosmetikbeutel','shared',1,'Organisation')}
 if(t.transport==='car'){add(a,'Kindersitz(e) prüfen','shared',1,'Auto');add(a,'Autoladekabel','shared',1,'Auto');add(a,'Müllbeutel fürs Auto','shared',2,'Auto')}
 return a;
}
function shell(c){return `<div class="shell">${c}<nav class="nav"><button type="button" class="${db.view==='home'?'active':''}" data-action="go" data-view="home">🏠<span>Reisen</span></button><button type="button" class="${db.view==='people'?'active':''}" data-action="go" data-view="people">👥<span>Personen</span></button><button type="button" class="${db.view==='templates'?'active':''}" data-action="go" data-view="templates">📋<span>Vorlagen</span></button><button type="button" class="${db.view==='more'?'active':''}" data-action="go" data-view="more">•••<span>Mehr</span></button></nav></div>`}
function home(){applyTheme('day');return shell(`<header class="hero"><div class="eyebrow">Deine persönliche Packassistentin ♡</div><div class="title">PackMe</div><div class="sub">Peinlich detailliert – du löschst, was du nicht brauchst.</div></header><main class="content"><button type="button" class="btn" data-action="go" data-view="new">＋ Neue Reise</button><h3>Meine Reisen</h3>${db.trips.map(tripCard).join('')||`<div class="empty">🧳<h3>Noch keine Reise</h3><p>Erstelle eine Reise und PackMe denkt mit.</p></div>`}</main>`)}
function tripCard(t){const done=t.items.filter(i=>i.done).length,total=t.items.length,pct=total?Math.round(done/total*100):0,th=themes[t.type]||themes.day;return `<div class="trip-card" data-id="${t.id}" style="--card-photo:url('${th.photo}')"><div class="trip-photo"></div><div class="trip-info"><div class="row space"><div class="trip-open" data-action="open-trip" data-id="${t.id}"><b>${esc(t.name)}</b><div class="small">${fmtDate(t.date)} · ${t.days} Tag${t.days>1?'e':''}</div></div><div class="trip-actions"><strong>${pct}%</strong><button type="button" class="iconbtn danger delete-trip" data-action="delete-trip" data-id="${t.id}" aria-label="Reise löschen">×</button></div></div><div class="progress"><i style="width:${pct}%"></i></div><div class="small trip-open" data-action="open-trip" data-id="${t.id}">${t.weather?`${codeIcon(t.weather.code)} ${t.weather.min}–${t.weather.max}° · Regen ${t.weather.rain}%`:'🌦️ Wetter'}</div></div></div>`}
function newView(){applyTheme('day');const today=new Date().toISOString().slice(0,10);return shell(`<header class="hero"><button type="button" class="back" data-action="go" data-view="home">‹ Zurück</button><div class="title">Neue Reise</div><div class="sub">Je genauer die Angaben, desto genauer die Packliste.</div></header><main class="content"><div class="card"><label>Wohin geht's?</label><input id="dest" class="input" placeholder="z. B. Velden, Prag, Gardasee"><label>Reiseart</label><div class="grid">${types.map((c,i)=>`<button type="button" class="choice ${i===0?'active':''}" data-action="select-type" data-type="${c[0]}">${c[1]}<br><b>${c[2]}</b></button>`).join('')}</div><label>Datum</label><input id="date" type="date" class="input" value="${today}"><div class="two"><div><label>Dauer</label><div class="stepper"><button type="button" data-action="step" data-n="-1">−</button><strong id="days">1</strong><button type="button" data-action="step" data-n="1">＋</button></div></div><div><label>Anreise</label><select id="transport" class="input"><option value="car">🚗 Auto</option><option value="train">🚆 Bahn</option><option value="plane">✈️ Flug</option><option value="other">Sonstiges</option></select></div></div><label>Übernachtung?</label><div class="seg"><button type="button" class="choice active" data-action="overnight" data-value="no">Nein</button><button type="button" class="choice" data-action="overnight" data-value="yes">Ja</button></div><label>Wer kommt mit?</label><div class="people">${db.people.map(p=>`<button type="button" class="person active" data-person="${p.id}">${p.kind==='child'?'👶':'👤'} ${esc(p.name)}</button>`).join('')}</div><label>Aktivitäten</label><div class="chips">${['Museum','Spazieren','Restaurant','Baden','Wandern','Shopping'].map(x=>`<button type="button" class="chip" data-chip="${x}">${x}</button>`).join('')}</div></div><button type="button" class="btn wide" data-action="create-trip">Intelligente Packliste erstellen →</button><p id="createStatus" class="muted center"></p></main>`)}
function selectType(el){document.querySelectorAll('.choice[data-type]').forEach(x=>x.classList.remove('active'));el.classList.add('active');applyTheme(el.dataset.type)}function overnight(el){document.querySelectorAll('[data-action="overnight"]').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
async function createTrip(){const s=document.querySelector('#createStatus'),dest=document.querySelector('#dest').value.trim()||'Mein Ausflug',date=document.querySelector('#date').value||new Date().toISOString().slice(0,10),days=Math.max(1,+document.querySelector('#days').textContent||1),type=document.querySelector('.choice[data-type].active')?.dataset.type||'day',people=[...document.querySelectorAll('[data-person].active')].map(x=>x.dataset.person),overnightFlag=document.querySelector('[data-action="overnight"].active')?.dataset.value==='yes',transport=document.querySelector('#transport').value,activities=[...document.querySelectorAll('[data-chip].active')].map(x=>x.dataset.chip);s.textContent='📍 Ort und Wetter werden geprüft …';let geo=null,w=null;try{geo=await geocode(dest);w=await getWeather(geo.latitude,geo.longitude,date,days)}catch(e){s.textContent='⚠️ Wetter nicht verfügbar – die detaillierte Grundliste wird trotzdem erstellt.'}const t={id:uid(),name:geo?.name||dest,date,days,type,people,overnight:overnightFlag,transport,activities,location:geo,weather:weatherSummary(w),items:[]};t.items=buildItems(t,t.weather);db.trips.unshift(t);db.current=t.id;db.view='trip';save();render()}
function openTrip(id){db.current=id;db.view='trip';save();render()}
function deleteTrip(id){const t=db.trips.find(x=>x.id===id);if(!t)return;if(!confirm(`"${t.name}" wirklich löschen? Die Packliste und der Fortschritt werden entfernt.`))return;db.trips=db.trips.filter(x=>x.id!==id);if(db.current===id){db.current=null;db.view='home'}save();render()}
function smartText(t,w){const b=[];if(t.days===1&&t.type==='day')b.push('Tagesausflug: Kleidung wird getragen; eingepackt werden echte Wechsel- und Notfallreserven.');if(t.days>1||t.overnight)b.push('Übernachtung: Schlafen, Pflege und Schmutzwäsche sind enthalten.');if(w){if(w.max>=23)b.push('warm → Sonnen-/Getränke-Reserve');if(w.min<14)b.push('kühl → zusätzliche Schicht');if(w.rain>=35)b.push('Regenrisiko → Regenausrüstung')}if(t.activities.length)b.push('Aktivitäten: '+t.activities.join(', ')+'.');return b.join(' ')}
function tripView(){const t=db.trips.find(x=>x.id===db.current);if(!t)return home();applyTheme(t.type);const w=t.weather,done=t.items.filter(i=>i.done).length,pct=Math.round(done/t.items.length*100),groups=[...new Set(t.items.map(i=>i.owner))];return shell(`<header class="hero trip-hero"><button type="button" class="back" data-action="go" data-view="home">‹ Reisen</button><div class="row space"><div><div class="title">${esc(t.name)}</div><div class="sub">${fmtDate(t.date)} · ${t.days} Tag${t.days>1?'e':''} · ${t.people.length} Personen</div></div><div class="percent">${pct}%</div></div><div class="progress"><i style="width:${pct}%"></i></div></header><main class="content"><div class="weather-card" style="background-image:url('${themes[t.type].photo}')"><div class="weather-overlay"><div>${t.location?esc(t.location.name):esc(t.name)}</div><div class="weather-big">${w?`${codeIcon(w.code)} ${w.max}°`:'🌦️'}</div><div>${w?`${w.min}° bis ${w.max}° · Regen ${w.rain}%`:'Wetter nicht verfügbar'}</div></div></div><div class="smart card"><b>🧠 Warum ist das dabei?</b><div class="small muted">${esc(smartText(t,w))}</div></div><div class="row space"><div><h3>Packliste</h3><div class="small muted">${t.items.length} Vorschläge · frei löschbar</div></div><span class="muted">${done}/${t.items.length}</span></div>${groups.map(g=>`<section class="list-card"><div class="section-title">${g==='shared'?'🧳 Gemeinsam':'👤 '+esc(ownerName(g))}</div>${t.items.filter(i=>i.owner===g).map(itemRow).join('')}</section>`).join('')}</main><button type="button" class="fab" data-action="add-item">＋</button>`)}
function itemRow(i){return `<div class="item swipe" data-id="${i.id}"><div class="item-icon">${iconFor(i)}</div><div class="item-main"><div class="item-name ${i.done?'done':''}">${esc(i.name)}</div><div class="small muted">${i.qty} ×${i.reason?' · '+esc(i.reason):''}</div></div><button type="button" class="iconbtn" data-action="toggle-item" data-id="${i.id}">${i.done?'↩':'✓'}</button><button type="button" class="iconbtn danger" data-action="delete-item" data-id="${i.id}">×</button></div>`}function iconFor(i){const n=i.name.toLowerCase();if(n.includes('windel'))return'🧷';if(n.includes('shirt'))return'👕';if(n.includes('hose'))return'👖';if(n.includes('sock'))return'🧦';if(n.includes('schlaf'))return'🌙';if(n.includes('sonnen'))return'🧴';if(n.includes('regen'))return'🌧️';if(n.includes('lade')||n.includes('power'))return'🔌';if(n.includes('zah'))return'🪥';if(n.includes('baden')||n.includes('strand'))return'🩱';if(n.includes('medizin')||n.includes('pflaster'))return'🩹';return'•'}
function toggleItem(id){const t=db.trips.find(x=>x.id===db.current),i=t?.items.find(x=>x.id===id);if(i)i.done=!i.done;save();render()}function deleteItem(id){const t=db.trips.find(x=>x.id===db.current);if(t)t.items=t.items.filter(x=>x.id!==id);save();render()}function addItem(){const n=prompt('Was möchtest du hinzufügen?');if(!n)return;const q=prompt('Wie viele?','1'),t=db.trips.find(x=>x.id===db.current);if(t)t.items.push({id:uid(),name:n,owner:'shared',qty:Math.max(1,Math.ceil(+q||1)),category:'Eigene Punkte',reason:'Von dir hinzugefügt',done:false});save();render()}
function peopleView(){applyTheme('day');return shell(`<header class="hero"><div class="title">Personen</div><div class="sub">Persönliche Mengen für spätere Reisen.</div></header><main class="content">${db.people.map(p=>`<div class="card"><b>${p.kind==='child'?'👶':'👤'} ${esc(p.name)}</b><div class="small muted">${p.kind==='child'?'Kind · Windeln/Tag: '+(p.diapers||5):'Erwachsene Person'}</div></div>`).join('')}<button type="button" class="btn" data-action="add-person">＋ Person hinzufügen</button></main>`)}
function addPerson(){const n=prompt('Name?');if(!n)return;const child=confirm('Ist es ein Kind?');const p={id:uid(),name:n,kind:child?'child':'adult'};Object.assign(p,child?{age:1,diapers:5,shirt:1.2,pants:.7,socks:1.2}:{shirt:1.1,pants:.55,underwear:1.1,socks:1.1});db.people.push(p);save();render()}
function templates(){applyTheme('day');return shell(`<header class="hero"><div class="title">Vorlagen</div><div class="sub">Fertige Reisen erneut verwenden.</div></header><main class="content">${db.trips.slice(0,8).map(t=>`<div class="card row space"><div><b>${esc(t.name)}</b><div class="small muted">${t.days} Tag${t.days>1?'e':''} · ${t.items.length} Punkte</div></div><button type="button" class="btn smallbtn" data-action="duplicate" data-id="${t.id}">Duplizieren</button></div>`).join('')||'<div class="empty">📋 Noch keine Vorlagen.</div>'}</main>`)}
function duplicateTrip(id){const old=db.trips.find(t=>t.id===id);if(!old)return;const t=JSON.parse(JSON.stringify(old));t.id=uid();t.date=new Date().toISOString().slice(0,10);t.items=t.items.map(i=>({...i,id:uid(),done:false}));db.trips.unshift(t);openTrip(t.id)}function more(){applyTheme('day');return shell(`<header class="hero"><div class="title">Mehr</div></header><main class="content"><div class="card"><b>🧠 Regelwerk</b><p class="muted">Die Masterliste ist bewusst großzügig. Reiseart, Dauer, Personen, Aktivitäten und Wetter bestimmen die Vorschläge.</p></div><div class="card"><b>👈➡️ Swipe</b><p class="muted">Rechts wischen = eingepackt, links = wieder offen.</p></div><div class="card"><b>💾 Lokal</b><p class="muted">Deine Daten bleiben im Browser.</p></div></main>`)}
function go(v){db.view=v;save();render()}function step(n){const e=document.querySelector('#days');if(e)e.textContent=Math.max(1,Math.min(30,+e.textContent+n))}
function render(){const c=db.view==='new'?newView():db.view==='trip'?tripView():db.view==='people'?peopleView():db.view==='templates'?templates():db.view==='more'?more():home();document.getElementById('app').innerHTML=c;enableSwipe()}
function enableSwipe(){document.querySelectorAll('.swipe').forEach(el=>{let sx=0;el.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>70){const t=db.trips.find(x=>x.id===db.current),i=t?.items.find(x=>x.id===el.dataset.id);if(i)i.done=dx>0;save();render()}})})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='go')go(b.dataset.view);else if(a==='open-trip')openTrip(b.dataset.id);else if(a==='select-type')selectType(b);else if(a==='overnight')overnight(b);else if(a==='step')step(+b.dataset.n);else if(a==='create-trip')createTrip();else if(a==='toggle-item')toggleItem(b.dataset.id);else if(a==='delete-item')deleteItem(b.dataset.id);else if(a==='add-item')addItem();else if(a==='add-person')addPerson();else if(a==='duplicate')duplicateTrip(b.dataset.id);else if(a==='delete-trip')deleteTrip(b.dataset.id)});document.addEventListener('click',e=>{const p=e.target.closest('[data-person]');if(p)p.classList.toggle('active');const c=e.target.closest('[data-chip]');if(c)c.classList.toggle('active')});render();
